### PR TITLE
[#246] add tutorials. remove legacy js getting started

### LINKED ISSUE #246: Deploy 3 - Right Code elimination, new tutorials
* `right-code` elimination (more mobile friendly)
* 7 new tutorials
* All js/py/rb tutorials are now pulled & compiled from active code repos
* elimination of legacy getting started

### PR DESCRIPTION
**Pull request by relativityboy**
Reviewers, please run the portal locally and check for errors/omissions. Comment and Approve/Request Changes when done.

Contributes to, but does not close #246

### CODE REVIEW

**Comment by inertia186** [comment]
I am seeing 404 errors when I use [SiteSucker](https://ricks-apps.com/osx/sitesucker/) to suck the whole site.

image

So, it turns out these links are wrong:

image

It's due to the use of relative links in the language tutorials.

**Comment by relativityboy** [comment]
@inertia186 @feruzm - regarding those broken links
1. we can etiher deploy with a couple broken links
1. point and pull https://github.com/steemit/devportal/issues/248 into the sprint as a sprint crasher (I recommend this only if we think we can get everything else done
1. file bugs on the repos that have broken-in-dp links and update them to be absolute links.

Which options are you in favor of?

**Comment by inertia186** [comment]
These links are not critical.  1 *and* 3 can be done simultaneously.  I'd be in favor of that.

**Comment by feruzm** [comment]
I am also in favor of 1 and 3, since Rob is OOO this week, current sprint will keep us busy

**Comment by relativityboy** [comment]
I'll defer to your collective wisdom, but FTR I think 1 & 2 are the better options.

**Pull request merged**
