### PR TITLE
Closes Contributors.md added to Devportal

### LINKED ISSUE #75: Create Contributors.md file to explain guidelines and contributing to the Devportal
Add contributors section to Devportal to explain best practices and how to contribute tutorials and information to the Devportal.

**AC**

- [x] Add Contributors section
- [x] Add Contributors nav item to top of navigation
- [x] Add Syntax Highlighter/prettifier guidelines

### PR DESCRIPTION
**Pull request by roboza**
Closes #75

### CODE REVIEW

**Comment by ayipeciaceh** [comment]
Good

**Comment by roboza** [comment]
Pushed updated to fix issues @relativityboy

**Comment by relativityboy** [comment]
@roboza - "Welcome to our API" is still missing. 
screen shot 2018-04-24 at 11 39 09 am

**Comment by relativityboy** [comment]
@roboza - After a local delete and re-pull "Welcome to our API" is still missing from the main nav.
screen shot 2018-04-24 at 11 39 09 am

**Pull request merged**
