### PR TITLE
Made 3 types of diagram

### PR DESCRIPTION
**Pull request by Prospector-au**

### CODE REVIEW

**Comment by inertia186** [comment]
Note, this is related to #398

**Comment by inertia186** [comment]
I think we should go with the high-contrast version, named `Diagram_steemd_00.png`.

Please delete the other two from this PR and rename `Diagram_steemd_00.png` to:

```
/images/tutorials-recipes/jussi-multiplexer/network-diagram.png
```

**Comment by roadscape** [comment]
@inertia186 is this still relevant?

**Comment by inertia186** [comment]
I think this can be closed.  It was part of an initiative under the Utopian umbrella that is no longer being managed.

**Pull request closed without merging**
